services:
  - type: web
    name: news-scraper
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: Backend/main.py
      - key: GOOGLE_CLIENT_KEY
        fromDatabase: GOOGLE_CLIENT_KEY
      - key: BACKEND_KEY
        fromDatabase: BACKEND_KEY