services:
  - type: web
    name: news-scraper
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: Backend/main.py
      - key: GOOGLE_CLIENT_KEY
        value: GOOGLE_CLIENT_KEY
      - key: BACKEND_KEY
        fromDatabase: BACKEND_KEY
      - key: DATABASE_URL
        fromDatabase: DATABASE_URL
    startCommand: gunicorn -w 4 -b 0.0.0.0:9000 Backend.main:app